import "./global.css";

export const metadata = {
  title: "DiscDuel",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-[#1DB954] min-h-screen">
        {children}
      </body>
    </html>
  );
}
